### PR TITLE
The media live stream - Initial commit with full stack in python

### PR DESCRIPTION
**Pull request by leandrodamascena**
First PR to the-media-live-stream CDK stack

cdk-patterns/serverless#120

### CODE REVIEW

**Comment by nideveloper** [comment]
I haven't had a chance to work through this yet but at an initial glance it looks awesome. Thanks for taking the time to put this into a PR

**Comment by leandrodamascena** [comment]
Don't worry @nideveloper. I had some busy days either... 
Let me know if I need to change anything in this PR, specially standards like variable names, constants, whatever..

medialive.CfnChannel component is too complex. There is a lot of dependence on specific types, so I tried to declare them in variables and inherit in the final component. If this is not a standard, let me know that I change and declare them in the component itself.

**Comment by leandrodamascena** [comment]
Hei @nideveloper. Let me know if you need any kind of help, adjusts or explanation here. Thank you.

**Comment by nideveloper** [comment]
Sorry, 
Weds are typically my cdk patterns day so good reminder. 

See this construct - https://github.com/leandrodamascena/serverless/blob/master/the-media-live-stream/python/the_media_live_stream/the_media_live_custom_mediapackage.py 

how production ready is it? Like could you create a JSII module and publish it to pypi/npm? Or would that really not make sense. I am just thinking people might want to use it directly... or is it because JSII has to start with TS and transpile to the other langs?

**Comment by leandrodamascena** [comment]
Hmm, it makes sense what you said to package and reuse it, just like you did SPADeploy, right?

Since the CDK does not implement native MediaPackage, I created this constructor on this stack using custom resources/api calls, but I agree that it can be reused as a component/package. I have to see how to adapt.

Do you want that I adapt it now or you prefer to use this stack and I update it in next commits?

**Comment by nideveloper** [comment]
Pahud has a good video on using projen to create a new construct, it's a lot easier now than when I created SPADeploy - https://www.youtube.com/watch?v=cTsSXYOYQPw 

I can't remember if we discussed the TypeScript version? I always launch with both, I am happy to pull this code into a branch and map over or do you want to do that version as well?

**Comment by leandrodamascena** [comment]
Nice @nideveloper. Thank you for sharing this video.

Hmm we didn't discuss about TS version but I'm very familiar with TS too. Let me know what you prefer :)

**Comment by nideveloper** [comment]
If you are happy to do TS as well then let's focus on getting the Python one perfect and then you can quickly map over to TS for us to launch.

I asked because for me given the two languages if that construct could be projen'd and published as a JSII construct it reduces the amount of work to map it over to TypeScript

**Comment by leandrodamascena** [comment]
Hello @nideveloper, only updating this PR.
I already did Construct to MediaPackage and is now public on NPM (https://www.npmjs.com/package/cdk-mediapackage-custom) and I'm finishing the adjustments for Pypi/Nuget.
I think this weekend I will refactor the code and launch the Stack in Python / TS using this Construct.

**Comment by leandrodamascena** [comment]
Hi @nideveloper, please forget about my last comment!

I checked today the latest version of the CDK and saw the "MediaPackage" resource was included, so it doesn't make much sense using a custom Constructor. I refactored the Stack and now it's very simple and using native resources 👍 

Please let me know if I can write this is Stack in TS to merge this PR :)

**Comment by nideveloper** [comment]
looks great, the only thing I would change is that I would move the website inside the python folder and duplicate it for the typescript. It seems counter productive but it means with the cdkp command line tool I can shallow clone one pattern in one language without pieces missing. When you add the TypeScript version the only thing over and above Python is please remember to add some unit tests

**Comment by leandrodamascena** [comment]
Updated the PR with TS Version + website folder inside languages folder + TS Tests

image

**Comment by cdk-patterns** [comment]
I merged this into a branch to just add a couple of things and will launch it later today. Great work, thanks

**Comment by nideveloper** [comment]
Hey, sorry to circle back round to this again but I always deploy and test the patterns before I launch them which is what has caused the delay. I was able to get both TS and Python deployed and connect to them to start streaming from OBS. The part that I cannot get working at all is the part where you view the stream, the included webpage just throws errors for me and if I try to connect to the stream with something else like vlc it also throws errors. So something feels like it is misconfigured in the stack, is there any way you could double check you haven't changed something locally that you forgot to commit? The code is over here now https://github.com/nideveloper/serverless/tree/master/the-media-live-stream I use my fork for changes. I updated the TS pattern to use string interpolation and added a deploy command that strings together the two manual deploys

**Comment by leandrodamascena** [comment]
Well.. let me check what is going on. I could deploy here with no problem, but let me check again! Thank you, dude!

**Comment by leandrodamascena** [comment]
Only one thing before start to debug here.. did you started the channel manually? Just to check.

**Comment by nideveloper** [comment]
Yeah it tells me the channel is started in the aws console but it also shows 5 status alert warnings. Same behaviour with both ts and python

**Comment by leandrodamascena** [comment]
Ok, I got it! When I added the TS version I changed the role creation and I forgot to add the policy to allow "mediaconnect" services. This IAM permissions allows medialive channel connect and send image/audio do mediapackage.  

My bad. I'm fixing and I'll make a PR into https://github.com/nideveloper/serverless/tree/master/the-media-live-stream.

**Pull request merged**
