### PR TITLE
Feature/the efs lambda stack csharp

### PR DESCRIPTION
**Pull request by leandrodamascena**
CSharp version of "the-efs-lambda" stack using CDK 1.78.0.

Please let me know if you want I update Python/TS stacks to latest CDK version or you'll run the update scripts. 

Ty.

### CODE REVIEW

**Comment by leandrodamascena** [comment]
Well... I think I created this branch from my master and that's where I developed "the-media-live-stream". You may experience problems merging this PR.

Let me know about.

**Comment by leandrodamascena** [comment]
Hi @nideveloper, let me know if you want I change anything in this PR. I have another 6 stacks rewritten in C#/Java.

Thanks.

**Comment by nideveloper** [comment]
Hey, with it being the holiday season I have been trying to take some time off and not code. 

It does look like the merge will be a bit of a nightmare though with all the media live stream changes coming through in both PRs at a point in time before I made changes. It would probably help if you pulled the latest changes into your branch.

Things that you need to look out for are things like requirements.txt has a lot of extra dependencies in it which I stripped out https://github.com/leandrodamascena/serverless/blob/feature/the-efs-lambda-stack-csharp/the-media-live-stream/python/requirements.txt vs https://github.com/cdk-patterns/serverless/blob/master/the-media-live-stream/python/requirements.txt and added the img folder so the images showed in the readme etc.

**Comment by leandrodamascena** [comment]
Ok ok don't worry!  It is assumed that everyone will have some time off this season.  I'm very active because I'm going to take a few days off in January haha.

Ok ok, I saw this and it will be very difficult to do the merger.  I isolated it on a new branch and I will close this PR and the other (there is the same problem, I think). I'll open again.

**Pull request closed without merging**
