### PR TITLE
The Simple Webservice CDK: Java edition

### PR DESCRIPTION
**Pull request by drissamri**
The current state of Java in CDK is a sad affair due to:
- CDK Java API Docs don't have working examples
- Cdkworkshop.com has some Java examples but then provides Lambda implementations in NodeJS/TypeScript
- Few examples & blogs on the web

I believe there's a lot of potential growth by Java shops (mostly big companies) that are hesitant to switch to other languages due to knowledge of employees, tooling and so on. 

### The Simple Webservice pattern in Java
I created a multi-module maven project that has two modules.
* CDK Java module
* Lambda Java module with the following "_best practices_":
    * [Optimized DynamoDB dependencies](https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/) for [faster cold starts](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/client-configuration-starttime.html) 
    * Packaging in reproducible ZIP (two builds with same source are identical, so CDK doesn't upload when nothing is changed)
    * Initialize dependencies in Constructor to leverage CPU burst during start up
    * [SLF4J + Logback ](https://blog.symphonia.io/posts/2017-01-17_love-letter-to-lambda-logging)

### Open issues
- [ ] No unit tests for CDK. I'm not sure what the best/easiest way to the JSON asserts
- [x] I think it would be nice to be able to run cdk deploy from the parent module somehow. Not sure how this would work.. Unless adding an extra package.json in root folder with run commands
- [ ] I added the pattern images to the README, not sure if they only have to be in the root pattern folder or duplicated in all implementation sub folders?

What else would you like to see @nideveloper? If this pattern has everything you want, I'll try converting some others too based on this example.

### CODE REVIEW

**Comment by nideveloper** [comment]
I had never used Java CDK before today. I decided to try it in cloud9 because that's how I maintain the python/typescript versions. Bit of a pain to get Java 11 on cloud9, much easier if people base it off Ubuntu rather than Amazon Linux 1. Mostly you can follow these steps https://docs.aws.amazon.com/cloud9/latest/user-guide/sample-java.html except for java 11 "sudo apt install -y openjdk-11-jdk" then mvn install, mvn test, cd cdk, npx cdk@1.56.0 deploy then worked  as expected. Adding a quick how to deploy with cloud9 section mighn't hurt. The reason Python/TS dont need that is because it is literally clone, install deps, deploy

**Comment by nideveloper** [comment]
The weird thing about cdk with all these other languages is that it is still a node module so when using Java CDK, you will still need to have node setup and working on your machine. So I am just wondering what the implication is of a package.json at the top level with a deploy task that does mvn install, test and then cd into cdk and runs cdk deploy. The cdk version would need to be kept in sync with the maven cdk version but today you would be in the same situation just manually

**Comment by drissamri** [comment]
I have no experience with Cloud9 yet, so not sure how easy/hard is to get started with, but you definitely need JDK & node installed (not maven because you can use the maven wrapper). Is this something I have to look into or do you want to add a getting started? 

I'm not sure yet how I feel about just adding the package.json to the root just to use npm run scripts. 
When using the Serverless Framework things are bit more clear since it's not a multi module project and you always have a package.json already in the root. In a way that makes things more understandable..

**Comment by nideveloper** [comment]
I have never used maven wrapper before, I see pom.xml and I just muscle memory install maven so maybe thats something to add to the readme why it is there.

You can do more with the package.json other than just use the scripts. You could actually define the cdk version as a dependency since it is a node module then when you run the script it will use the locked version. Just another way to avoid global cdk install other than the npx route defined above. 

I am keen for all the language implementations to be simple to use - clone, cd into folder, install dependencies, deploy. 

I try not to differ from how AWS define the structure so that examples all relate - https://github.com/aws-samples/aws-cdk-examples/tree/master/java/lambda-cron. The problem is they haven't bundled a java lambda in any of them

**Comment by drissamri** [comment]
Do we have any strong opinions on the AWS / CDK team on structuring Java apps? 
cc @msailes @SaschaMoellering @RomainMuller

**Comment by nideveloper** [comment]
To get a baseline for "the java cdk way", I was looking at the java examples above and the "cdk init sample-app --language java". Both of those setups have the cdk pom.xml at the top level with a src folder containing the cdk code. I noticed the example apps use a resource folder for things like lambda functions which could again have their own pom that you link up the way you have here.

Without having these languages in production for a while to know the pros/cons it is hard to say but I would suggest we stick to the way aws are doing it until we workout why we would change it and then we maybe open an issue on cdk for the starter template and the examples

**Comment by drissamri** [comment]
I've been a bit busy at work, let me pick this up over the weekend. I have some idea's to try out 🎈 

It would be nice though to find someone over at the AWS dev advocates or CDK team that has Java experience to have a little chat, but not sure who to ping yet.

**Comment by drissamri** [comment]
Sorry for the delay @nideveloper. Stuff came up, holiday start & ended in meanwhile so ready to go again!

I reorganized it like you said, but this was really unnatural for me as a Java/Maven developer. All those examples never implement Java for CDK and resources I think? The best example I found in the official examples is: https://github.com/aws-samples/aws-cdk-examples/tree/master/java/api-cors-lambda-crud-dynamodb 

I took that as a base with some tweaks that I'd like to submit to that example too.
Now you can checkout and run `./mvnw package` & `cdk deploy` from the root folder 🥳 The most important part is specifying the module you want CDK to use in `cdk.json`
```
  "app": "mvn compile exec:java -pl cdk",
```

What do you think about this?

**Comment by nideveloper** [comment]
The cdk deploy step failed for me after running "./mvnw package" because you need maven installed. What have I done wrong?

Screenshot 2020-09-12 at 09 42 27

**Comment by drissamri** [comment]
The cdk.json was still refering to mvn instead of ./mvnw (wrapper). I changed and pushed it, can you try again? 

I'm not sure how this will respond on Windows machines due to there mvnw.cmd also being there, not sure if this is automatically picked up or not. 

There is also a maven plugin that wraps the cdk node package, so you don't need nodejs/cdk installed and can do everything from Maven but I'm not entirely sure that is the right path to take. You loose the flexibility of the CDK npm plugins etc: https://github.com/LinguaRobot/aws-cdk-maven-plugin

**Comment by nideveloper** [comment]
I'm on Ubuntu not Windows but that change worked for me

**Comment by nideveloper** [comment]
Is "./mvnw test" meant to run LambdaHandlerTest? I don't think it does today

**Comment by drissamri** [comment]
Eagle eye! Fixed by explicitly setting the surefire plugin since the default version still doesn't pick up JUnit 5 tests automatically. 

```
[INFO] Running com.cdkpatterns.LambdaHandlerTest
[2020-09-12 12:03:36.420] NO-REQUEST-ID INFO c.c.LambdaHandler - Request: APIGatewayV2HTTPEvent(version=null, routeKey=null, rawPath=null, rawQueryString=null, cookies=null, headers=null, queryStringParameters=null, pathParameters=null, stageVariables=null, Body=null, isBase64Encoded=false, requestContext=null) 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1 s - in com.cdkpatterns.LambdaHandlerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by nideveloper** [comment]
It definitely still isn't running the tests for me even after pulling the latest code. After the test runs I think this is perfect to merge

Screenshot 2020-09-14 at 08 33 15

**Comment by drissamri** [comment]
The test folder structure was wrong *doh*, when you ran it in IntelliJ then maven would pick it up until you do clean.
Fixed it, ./mvnw clean package 

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.cdkpatterns.LambdaHandlerTest
[2020-10-24 14:13:32.488] NO-REQUEST-ID INFO c.c.LambdaHandler - Request: APIGatewayV2HTTPEvent(version=null, routeKey=null, rawPath=null, rawQueryString=null, cookies=null, headers=null, queryStringParameters=null, pathParameters=null, stageVariables=null, Body=null, isBase64Encoded=false, requestContext=null) 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.998 s - in com.cdkpatterns.LambdaHandlerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
```

If this one gets merged I'll start working on other patterns

**Comment by nideveloper** [comment]
Great job, cloned and built / ran the tests today - all working as expected. LGTM!

**Pull request merged**
