### PR TITLE
C# The Simple Webservice

### PR DESCRIPTION
**Pull request by mho105**
Hello,

I'd like to kick off a discussion around getting some C# examples in the repo,I've been using the CDK at work for the past couple of months and found the patterns really useful.

I've started with the simple webservice but can provide some other patterns once a C# baseline has been established.

I've tried to keep it inline with the way that the official aws examples are structured, you should just be able to run cdk deploy from root.

Happy for any feedback or to make changes. I've read the comments of the Java version, would cloud9 documentation be useful?

Thanks,

Mark

### CODE REVIEW

**Comment by cdk-patterns** [comment]
awesome, thanks for the PR. cloud9 docs would definitely be useful for me personally. The reason they aren't needed for TS/Python is because cloud9 works with those out of the box. Other than that this looks perfect

**Comment by cdk-patterns** [comment]
I'm not a .net developer so is this where you would lock the versions? https://github.com/mho105/serverless/blob/csharp-the-simple-webservice/the-simple-webservice/csharp/src/TheSimpleWebservice/TheSimpleWebservice.csproj#L9 I tend to lock the versions in cdk patterns because it means I can upgrade them on my schedule and not worry about breaking changes

**Comment by mho105** [comment]
I'll add some cloud9 docs.

I personally would always lock the versions but I noticed that the aws examples didn't:
e.g. https://github.com/aws-samples/aws-cdk-examples/blob/master/csharp/capitalize-string/src/CapitalizeString/CapitalizeString.csproj

I'll make that change as well as it makes more sense.

**Comment by mho105** [comment]
I've added both. It's the first time using Cloud9 so any feedback would be good.

Please excuse the horrible spelling of explicitly 😬

**Comment by cdk-patterns** [comment]
I just followed your cloud9 instructions from a new instance and deployed the stack with no issues. Let's get this merged!

**Pull request merged**
